name: QA Automation Regression Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  automation-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el código del repositorio
      uses: actions/checkout@v3

    - name: Configurar Java JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'maven'

    - name: Ejecutar Pruebas de UI (Selenium en modo Headless)
      run: |
        cd automation-frameworks/java-testng-selenium
        mvn clean test -Dheadless=true

    - name: Guardar Reportes como Artefactos
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: testng-execution-reports
        path: automation-frameworks/java-testng-selenium/target/surefire-reports/
